"""
Django settings for DjangoProjectLMS_V1 project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-eksy&y%u2hzay@cq=(x(em(603u^2%b7z3w@sd1387@*cq&x=f')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Allowed hosts - supports both local and Railway
ALLOWED_HOSTS = [
    'djangoprojectlmsv1-production.up.railway.app',  # Railway production
    'localhost',                                      # Local development
    '127.0.0.1',                                     # Local development alternative
]

# CSRF settings for Railway deployment
CSRF_TRUSTED_ORIGINS = [
    'https://djangoprojectlmsv1-production.up.railway.app',  # Railway production
    'http://localhost:8000',                                  # Local development
    'http://127.0.0.1:8000',                                 # Local development alternative
]

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'Person.apps.PersonConfig',
    'AcademicStructure.apps.AcademicstructureConfig',
    'FacultyModule.apps.FacultymoduleConfig',
    'StudentModule.apps.StudentmoduleConfig',
    'pages.apps.PagesConfig',
    'accounts.apps.AccountsConfig',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Person.middleware.AuditMiddleware',

]

ROOT_URLCONF = 'DjangoProjectLMS_V1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProjectLMS_V1.wsgi.application'

# Database configuration - Railway vs Local
if os.environ.get('RAILWAY_ENVIRONMENT'):
    # Production (Railway) - Hardcoded MySQL connection
    DATABASES = {
        'default': {
            'ENGINE': 'mysql.connector.django',
            'NAME': 'railway',
            'USER': 'root',
            'PASSWORD': 'OfIdpzYBYZLTWhASnwvGOPqpKrsNGWVU',
            'HOST': 'crossover.proxy.rlwy.net',
            'PORT': 58556,
            'OPTIONS': {
                'autocommit': True,
            },
        }
    }
    print("Using Railway MySQL database")
else:
    # Local development - Your PC MySQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'LMS',
            'USER': 'root',
            'PASSWORD': '@databaselab123',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }
    print("Using local MySQL database")

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files configuration for WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Additional static files settings
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if (BASE_DIR / 'static').exists() else []