# Generated by Django 5.2.1 on 2025-06-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Graduated', 'Graduated'), ('Dropped', 'Dropped')], default='Enrolled', max_length=9),
        ),
    ]
