# Generated by Django 5.2.1 on 2025-07-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentModule', '0002_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], db_column='status', default='Active', max_length=9),
        ),
    ]
