# Generated by Django 5.2.1 on 2025-07-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentModule', '0003_alter_enrollment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='createdat',
            new_name='createdate',
        ),
        migrations.AddField(
            model_name='result',
            name='obtainedMarks',
            field=models.DecimalField(db_column='obtained', decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('obtainedMarks__gte', 0), ('obtainedMarks__lte', 100)), name='valid_obtained_marks_range'),
        ),
    ]
