# Generated by Django 5.2.1 on 2025-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.CharField(db_column='personID', max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(db_column='fname', max_length=50)),
                ('lname', models.CharField(db_column='lname', max_length=50)),
                ('personalemail', models.CharField(blank=True, db_column='personalEmail', max_length=50, null=True)),
                ('institutionalemail', models.CharField(db_column='institutionalEmail', max_length=50, unique=True)),
                ('cnic', models.CharField(db_column='CNIC', max_length=15)),
                ('gender', models.CharField(db_column='gender', max_length=1)),
                ('dob', models.DateField(db_column='DOB')),
                ('cnumber', models.CharField(db_column='cNumber', max_length=15)),
                ('type', models.CharField(db_column='type', max_length=7)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
