# Generated by Django 5.2.1 on 2025-06-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
        ('StudentModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('alumniid', models.OneToOneField(db_column='alumniID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudentModule.student')),
                ('graduationdate', models.DateField(db_column='graduationDate')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('employmentinfo', models.TextField(blank=True, db_column='employmentInfo', null=True)),
            ],
            options={
                'db_table': 'alumni',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('personid', models.OneToOneField(db_column='personID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Person.person')),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(db_column='zipCode')),
                ('streetaddress', models.CharField(blank=True, db_column='streetAddress', max_length=100, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('employeeid', models.OneToOneField(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Person.person')),
                ('joiningdate', models.DateField(db_column='joiningDate')),
                ('leavingdate', models.DateField(blank=True, db_column='leavingDate', null=True)),
                ('officelocation', models.CharField(blank=True, db_column='officeLocation', max_length=100, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Audittrail',
            fields=[
                ('auditid', models.AutoField(db_column='auditID', primary_key=True, serialize=False)),
                ('actiontype', models.CharField(db_column='actionType', max_length=6)),
                ('entityname', models.CharField(db_column='entityName', max_length=50)),
                ('timestamp', models.DateTimeField(db_column='timeStamp')),
                ('ipaddress', models.CharField(db_column='IPaddress', max_length=45)),
                ('useragent', models.CharField(db_column='userAgent', max_length=255)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
            ],
            options={
                'db_table': 'audittrail',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualificationid', models.AutoField(db_column='qualificationID', primary_key=True, serialize=False)),
                ('degreetitle', models.CharField(db_column='degreeTitle', max_length=50)),
                ('educationboard', models.CharField(blank=True, db_column='educationBoard', max_length=20, null=True)),
                ('institution', models.CharField(max_length=50)),
                ('passingyear', models.TextField(blank=True, db_column='passingYear', null=True)),
                ('totalmarks', models.IntegerField(blank=True, db_column='totalMarks', null=True)),
                ('obtainedmarks', models.IntegerField(blank=True, db_column='obtainedMarks', null=True)),
                ('iscurrent', models.IntegerField(blank=True, db_column='isCurrent', null=True)),
                ('personid', models.ForeignKey(db_column='personID', on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
            ],
            options={
                'db_table': 'qualification',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salaryid', models.AutoField(db_column='salaryID', primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentdate', models.DateField(db_column='paymentDate')),
                ('employeeid', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
            ],
            options={
                'db_table': 'salary',
                'unique_together': {('employeeid', 'year', 'month')},
            },
        ),
    ]
