# Generated by Django 5.2.1 on 2025-07-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0004_changerequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changerequest',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='changerequest',
            table='change_request',
        ),
    ]
