# Generated by Django 5.2.1 on 2025-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessmentid', models.AutoField(db_column='assessmentID', primary_key=True, serialize=False)),
                ('assessmenttype', models.CharField(db_column='assessmentType', max_length=10)),
                ('assessmentname', models.CharField(db_column='assessmentName', max_length=20)),
                ('weightage', models.IntegerField()),
                ('assessmentdate', models.DateField(blank=True, db_column='assessmentDate', null=True)),
                ('totalmarks', models.IntegerField(db_column='totalMarks')),
            ],
            options={
                'db_table': 'assessment',
            },
        ),
        migrations.CreateModel(
            name='Assessmentchecked',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('obtained', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'assessmentchecked',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('attendancedate', models.DateTimeField(db_column='attendanceDate')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Courseallocation',
            fields=[
                ('allocationid', models.AutoField(db_column='allocationID', primary_key=True, serialize=False)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'courseallocation',
            },
        ),
    ]
