# Generated by Django 5.2.1 on 2025-06-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicStructure', '0001_initial'),
        ('FacultyModule', '0001_initial'),
        ('Person', '0001_initial'),
        ('StudentModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentchecked',
            name='assessmentid',
            field=models.ForeignKey(db_column='assessmentID', on_delete=django.db.models.deletion.CASCADE, to='FacultyModule.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentchecked',
            name='enrollmentid',
            field=models.ForeignKey(db_column='enrollmentID', on_delete=django.db.models.deletion.CASCADE, to='StudentModule.enrollment'),
        ),
        migrations.AddField(
            model_name='assessmentchecked',
            name='resultid',
            field=models.ForeignKey(db_column='resultID', on_delete=django.db.models.deletion.CASCADE, to='StudentModule.result'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='studentid',
            field=models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='StudentModule.student'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='coursecode',
            field=models.ForeignKey(db_column='courseCode', on_delete=django.db.models.deletion.RESTRICT, to='AcademicStructure.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='allocationid',
            field=models.ForeignKey(db_column='allocationID', on_delete=django.db.models.deletion.CASCADE, to='FacultyModule.courseallocation'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('employeeid', models.OneToOneField(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Person.person')),
                ('designation', models.CharField(max_length=50)),
                ('joiningdate', models.DateField(db_column='joiningDate')),
                ('departmentid', models.ForeignKey(db_column='departmentID', on_delete=django.db.models.deletion.RESTRICT, to='AcademicStructure.department')),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='teacherid',
            field=models.ForeignKey(db_column='teacherID', on_delete=django.db.models.deletion.RESTRICT, to='FacultyModule.faculty'),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lectureno', models.IntegerField(db_column='lectureNo')),
                ('lectureid', models.CharField(db_column='lectureID', max_length=10, primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=50)),
                ('startingtime', models.DateTimeField(db_column='startingTime')),
                ('endingtime', models.DateTimeField(db_column='endingTime')),
                ('topic', models.TextField(blank=True, null=True)),
                ('allocationid', models.ForeignKey(db_column='allocationID', on_delete=django.db.models.deletion.CASCADE, to='FacultyModule.courseallocation')),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='lectureid',
            field=models.ForeignKey(db_column='lectureID', on_delete=django.db.models.deletion.CASCADE, to='FacultyModule.lecture'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentchecked',
            unique_together={('assessmentid', 'enrollmentid')},
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('teacherid', 'coursecode', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('attendancedate', 'studentid', 'lectureid')},
        ),
    ]
