# Generated by Django 5.2.1 on 2025-06-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyModule', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together=set(),
        ),
    ]
