# Generated by Django 5.2.1 on 2025-07-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyModule', '0003_alter_courseallocation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='status', default='Ongoing', max_length=9),
        ),
    ]
