# Generated by Django 5.2.1 on 2025-06-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.AutoField(db_column='classID', primary_key=True, serialize=False)),
                ('batchyear', models.TextField(db_column='batchYear')),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(db_column='departmentID', primary_key=True, serialize=False)),
                ('departmentname', models.CharField(db_column='departmentName', max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programid', models.CharField(db_column='programID', max_length=10, primary_key=True, serialize=False)),
                ('programname', models.CharField(db_column='programName', max_length=50)),
                ('totalsemesters', models.IntegerField(db_column='totalSemesters')),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterid', models.AutoField(db_column='semesterID', primary_key=True, serialize=False)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('semesterno', models.IntegerField(db_column='semesterNo')),
            ],
            options={
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='Semesterdetails',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'semesterdetails',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('coursecode', models.CharField(db_column='courseCode', max_length=20, primary_key=True, serialize=False)),
                ('coursename', models.CharField(db_column='courseName', max_length=50)),
                ('credithours', models.IntegerField(db_column='creditHours')),
                ('description', models.TextField(blank=True, null=True)),
                ('prerequisite', models.ForeignKey(blank=True, db_column='preRequisite', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AcademicStructure.course')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
