# Generated by Django 5.2.1 on 2025-06-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicStructure', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programid',
        ),
    ]
