# Generated by Django 5.2.1 on 2025-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicStructure', '0003_remove_course_programid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursename',
            field=models.CharField(db_column='courseName', max_length=100),
        ),
    ]
