# Generated by Django 5.2.1 on 2025-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicStructure', '0004_alter_course_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='fee',
        ),
        migrations.AddField(
            model_name='program',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
