# Generated by Django 5.2.1 on 2025-06-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicStructure', '0006_semester_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Inactive', max_length=9),
        ),
    ]
