# Generated by Django 5.2.1 on 2025-06-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicStructure', '0008_remove_semesterdetails_session_semester_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Inactive', max_length=15),
        ),
    ]
