# Generated by Django 5.2.1 on 2025-06-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicStructure', '0009_alter_semester_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='session',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
